name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["2.7", "3.4", "3.6"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up pyenv
        uses: gabrielfalcao/pyenv-action@v18
        with:
          default: ${{ matrix.python-version }}
          versions: ${{ matrix.python-version }}
          command: pip install -U pip  # Upgrade pip after installing Python

      - name: Install dependencies
        run: |
          echo "yes" | sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
          sudo apt-get update -qq
          sudo apt-get install -qq g++-4.8 libstdc++-4.8-dev
          export CXX="g++-4.8" CC="gcc-4.8"
          sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 90
          sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 90
          echo "CXX=$CXX"
          echo "version `$CXX --version`"

      - name: Build and install
        run: |
          python setup.py clean build sdist install