name: Using
on: [push, pull_request]

jobs:
  my_python_job:
    name: "Python"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python:
          - 3.8.16
          - 3.9

    steps:
      - uses: actions/checkout@v4
      - name: Install python version
        uses: gabrielfalcao/pyenv-action@v18
        with:
          default: "${{ matrix.python }}"
          command: pip install -U pip  # upgrade pip after installing python

      - name: Run tests
        run: python --version
