name: Workflow
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  my_python_job:
    name: "Python"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python:
          - 2.7.18
          - 3.4.10
          - 3.6.15
          - 3.8.10
          - 3.10.12

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update; sudo apt install build-essential libssl-dev zlib1g-dev \
          libbz2-dev libreadline-dev libsqlite3-dev curl git \
          libncursesw5-dev xz-utils tk-dev libxml2-dev libxmlsec1-dev libffi-dev liblzma-dev

      - name: Install python version
        uses: gabrielfalcao/pyenv-action@v18
        with:
          default: "${{ matrix.python }}"
          command: pip install -U pip  # upgrade pip after installing python

      - name: Build and install
        run: python setup.py clean build sdist install
